- name: Install PyMySQL
  pip:
    name: pymysql
    state: present
    
- name: create database
  community.mysql.mysql_db:
    login_host: "terraform-20240108204309556400000001.crbutbf4xddp.us-east-1.rds.amazonaws.com"
    login_user: "admin"
    login_password: "kipkulei123"
    name: toolingdb
    collation: utf8_general_ci
    encoding: utf8
    state: present

- name: Input tooling credentials
  ansible.builtin.replace:
    path: /var/www/html/functions.php
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  loop:
    - { regexp: '^mysql.tooling.svc.cluster.local', line: "terraform-2024010814305577360000000a.crbutbf4xddp.us-east-1.rds.amazonaws.com" }
    - { regexp: '^admin', line: "admin" }
    - { regexp: '^tooling', line: "toolingdb" }
    - { regexp: '^admin', line: "kipkulei123" }


