--- 
 - hosts: tag_name_DEV_nginx
 - name:  nginx assignment 
   import_playbook: ../static-assignments/nginx.yml

 - hosts: tag_name_DEV_tooling
 - name: Tooling assignment
   import_playbook: ../static-assignments/tooling.yml

 - hosts: tag_name_DEV_tooling
 - name: Tooling assignment
   import_playbook: ../static-assignments/wordpress.yaml


 
 - hosts: tag_name_DEV_tooling
 - name: Tooling assignment
   import_playbook: ../static-assignments/jenkins.yml

 - hosts: tag_name_DEV_tooling
 - name: Tooling assignment
   import_playbook: ../static-assignments/jfrog.yml

 - hosts: tag_name_DEV_tooling
 - name: Tooling assignment
   import_playbook: ../static-assignments/sonar.yml

